### ISSUE TITLE
Image rotation bug with photos taken from cameras in vertical position

### ISSUE THREAD

**Issue by Ricardo50** [shish/shimmie2#731] opened 2020-06-13 18:22 UTC
**Server Software**

> Optional:
> Site title: Shimmie
> Theme: default
> Genre: [describe your site here]
> URL: http://192.168.0.6
> 
> System stats:
> Shimmie: 2.8.0
> Schema: 18
> PHP: 7.4.7
> OS: Linux SRV06 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
> Database: mysql
> Server: Apache/2.4.29 (Ubuntu)
> Disk use: 34.1GB / 60.9GB
> 
> Media System:
> Memory Limit: 8388608
> 
> Thumbnail Generation:
> Engine: convert
> Type: jpg
> Quality: 100
> Width: 192
> Height: 192
> Scaling: 100
> 
> Shimmie stats:
> Images: 9
> Comments: 0
> Users: 3
> Tags: 10
> Applications: 16
> Extensions: AliasEditor, BBCode, CommentList, ExtManager, FourOhFour, PixelFileHandler, HelpPages, ImageIO, Index, Media, Setup, StaticFiles, System, TagEdit, TagList, Upgrade, Upload, UserPage, UserConfig, ViewImage, AdminPage, Blotter, BrowserSearch, DanbooruApi, Emoticons, EmoticonList, ET, Favorites, Featured, FlashFileHandler, IcoFileHandler, MP3FileHandler, SVGFileHandler, VideoFileHandler, Home, ImageBan, ImageViewCounter, IPBan, NumericScore, Ratings, RegenThumb, ReportImage, RotateImage, SiteDescription, SourceHistory, TagHistory, TranscodeImage, Trash, Update, Wiki
> 

 - Shimmie version: 2.8.0
 - Database: mysql
 - Web server: apache

**Client Software (please complete the following information)**
 - Device: Windows Desktop
 - Browser: Firefox 77.0.1

**What steps trigger this bug**
1. Upload a picture from a phone or tablet device that was taken in vertical view
1. In full image view the photo will be displayed correctly (vertical)
1. In the thumbnail view the picture will be swapped to the horizontal position

**What did you expect to happen?**
1. EXIF data should be read to determine the rotation before writing the width and height to the database.
1. Also the thumbnailer script should rotate the image

**What actually happened?**

The thumbnail looks like this:
![afbeelding](https://user-images.githubusercontent.com/24867787/84576163-e9695600-adb2-11ea-8478-f1be1afa855f.png)

But the full view is correct:
![afbeelding](https://user-images.githubusercontent.com/24867787/84576196-25042000-adb3-11ea-9cc8-dc88de83917d.png)

Width and height in DB are incorrect
![afbeelding](https://user-images.githubusercontent.com/24867787/84576239-73b1ba00-adb3-11ea-91ae-e81a862cb93c.png)

**Comment by shish** [comment] 2024-01-04 18:00
I think this should be fixed with updated image libraries, at least I can't reproduce it myself - if this is still happening, feel free to reopen and please attach an image that triggers the problem so that I can test with exactly the same file ^^

**Closed by shish** 2024-01-04 18:00 UTC
Labels: Bug
